/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * userListResponse schema
 */
export interface UserListResponse {
  /**
   * userId
   */
  id?: number;
  /**
   * primary_account_type
   */
  primaryAccountType?: string;
  /**
   * username
   */
  username?: string;
  /**
   * display_name
   */
  displayName?: string;
  /**
   * email
   */
  email?: string;
  /**
   * phone_code
   */
  phoneCode?: string;
  /**
   * phone_number
   */
  phoneNumber?: string;
  /**
   * avatar
   */
  avatar?: string;
  /**
   * domain
   */
  domain?: string;
  /**
   * birthday
   */
  birthday?: string;
  [k: string]: any;
}
